---
# SSH hardening defaults

ssh_hardening_permit_root_login: "no"
ssh_hardening_password_authentication: "no"
ssh_hardening_pubkey_authentication: "yes"

ssh_hardening_max_auth_tries: 4
ssh_hardening_login_grace_time: 60

ssh_hardening_x11_forwarding: "no"
ssh_hardening_ignore_rhosts: "yes"
ssh_hardening_hostbased_authentication: "no"

ssh_hardening_client_alive_interval: 300
ssh_hardening_client_alive_count_max: 3
