---
# Critical filesystem permission hardening defaults

filesystem_permissions_debian:
  - path: /etc/passwd
    owner: root
    group: root
    mode: "0644"

  - path: /etc/group
    owner: root
    group: root
    mode: "0644"

  - path: /etc/shadow
    owner: root
    group: shadow
    mode: "0640"

  - path: /etc/gshadow
    owner: root
    group: shadow
    mode: "0640"

filesystem_permissions_redhat:
  - path: /etc/passwd
    owner: root
    group: root
    mode: "0644"

  - path: /etc/group
    owner: root
    group: root
    mode: "0644"

  - path: /etc/shadow
    owner: root
    group: root
    mode: "0000"

  - path: /etc/gshadow
    owner: root
    group: root
    mode: "0000"
