---
- name: Configure Debian Linux systems
  hosts: debian
  become: true
  gather_facts: true

  roles:
    - role: linux_baseline
      tags:
        - baseline

    - role: debian_packages
      tags:
        - packages

    - role: vim_configuration
      tags:
        - vim

    - role: user_management
      tags:
        - users

    - role: sudo_configuration
      tags:
        - sudo

    - role: node_exporter
      tags:
        - node_exporter


- name: Configure CentOS Linux systems
  hosts: centos
  become: true
  gather_facts: true

  roles:
    - role: linux_baseline
      tags:
        - baseline

    - role: centos_packages
      tags:
        - packages

    - role: vim_configuration
      tags:
        - vim

    - role: user_management
      tags:
        - users

    - role: sudo_configuration
      tags:
        - sudo

    - role: node_exporter
      tags:
        - node_exporter
- name: Configure RHEL Linux systems
  hosts: rhel
  become: true
  gather_facts: true

  roles:
    - role: linux_baseline
      tags:
        - baseline

    - role: centos_packages
      tags:
        - packages

    - role: vim_configuration
      tags:
        - vim

    - role: user_management
      tags:
        - users

    - role: sudo_configuration
      tags:
        - sudo

    - role: node_exporter
      tags:
        - node_exporter
