---
all:
  vars:
    ansible_user: afernandez

  children:
    control:
      hosts:
        debian12bigone:
          ansible_host: 192.168.0.144

    debian:
      hosts:
        debian2:
          ansible_host: 192.168.0.97
        xpsdebian:
          ansible_host: 192.168.0.78
        debian12bigone:
          ansible_host: 192.168.0.144
        debian12vmwindows:
          ansible_host: 192.168.0.3
        debian12lenovo:
          ansible_host: 192.168.0.182
        debianwindows:
          ansible_host: 192.168.0.31
        debian4:
          ansible_host: 192.168.0.214

    centos:
      hosts:
        centos9:
          ansible_host: 192.168.0.125
        centos2:
          ansible_host: 192.168.0.100
